# Translation of Odoo Server.
# This file contains the translation of the following modules:
# 	* edi_account_invoice_import
#
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 14.0\n"
"Report-Msgid-Bugs-To: \n"
"Last-Translator: \n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Plural-Forms: \n"

#. module: edi_account_invoice_import
#: model_terms:ir.ui.view,arch_db:edi_account_invoice_import.message_already_imported
msgid "<strong>Invoice:</strong>"
msgstr ""

#. module: edi_account_invoice_import
#: model_terms:ir.ui.view,arch_db:edi_account_invoice_import.message_already_imported
msgid "<strong>Message:</strong>"
msgstr ""

#. module: edi_account_invoice_import
#: model_terms:ir.ui.view,arch_db:edi_account_invoice_import.message_already_imported
msgid "<strong>Previous record:</strong>"
msgstr ""

#. module: edi_account_invoice_import
#: code:addons/edi_account_invoice_import/components/process.py:0
#, python-format
msgid "Invoice %s created"
msgstr ""

#. module: edi_account_invoice_import
#: code:addons/edi_account_invoice_import/components/process.py:0
#, python-format
msgid "Invoice has already been imported before"
msgstr ""

#. module: edi_account_invoice_import
#: code:addons/edi_account_invoice_import/components/process.py:0
#, python-format
msgid "Something went wrong with the importing wizard."
msgstr ""
